### ISSUE TITLE
Strange Chat Avatar

### ISSUE THREAD

**Issue by hulk1st** [overleaf/chat#1]
For all chats I did so far, the users had the same avatar which is this one: http://www.gravatar.com/avatar/92657602ed6277cacd1d809672df0b21?d=mm&s=50

However, I have one user that always has this one:
http://www.gravatar.com/avatar/d3c114d5a943eb41e4041d13d95c6afc?d=mm&s=50

I first thought he found a way to change this in his profile but he had no idea. Is this intentionally?

**Comment by jpallen** [comment]
The avatar is based on the user's email and the avatar that they have configured for that in Gravatar. Changing the email, or the avatar in Gravatar will change the avatar.

Regards,
James
